import { supabase } from './supabase'

async function userId() {
  const { data, error } = await supabase.auth.getUser()
  if (error || !data.user) throw new Error('You must be signed in.')
  return data.user.id
}

export async function getProfile() { const id = await userId(); const { data, error } = await supabase.from('profiles').select('*').eq('id', id).single(); if (error) throw error; return data }
export async function updateProfile(values: { full_name?: string; role?: string; phone?: string }) { const id = await userId(); const { data, error } = await supabase.from('profiles').update(values).eq('id', id).select().single(); if (error) throw error; return data }

export async function getMyClasses(role: string) {
  const id = await userId()
  if (role === 'teacher') { const { data, error } = await supabase.from('classes').select('*').eq('teacher_id', id).eq('is_active', true).order('created_at', { ascending: false }); if (error) throw error; return data || [] }
  const { data, error } = await supabase.from('class_students').select('class_id, classes(*)').eq('student_id', id); if (error) throw error; return (data || []).map((x:any)=>x.classes).filter(Boolean)
}
export async function getClassStudents(classId:string) { const {data,error}=await supabase.from('class_students').select('student_id, profiles:student_id(id,full_name)').eq('class_id',classId); if(error) throw error; return data||[] }
export async function createClass(values:{name:string;grade_level?:string;description?:string}) { const id=await userId(); const join_code=Math.random().toString(36).slice(2,8).toUpperCase(); const {data,error}=await supabase.from('classes').insert({...values,teacher_id:id,join_code}).select().single(); if(error) throw error; return data }
export async function joinClass(code:string) { const id=await userId(); const {data:cls,error:findError}=await supabase.from('classes').select('id,name').eq('join_code',code.trim().toUpperCase()).eq('is_active',true).single(); if(findError) throw new Error('Class code not found.'); const {error}=await supabase.from('class_students').insert({class_id:cls.id,student_id:id}); if(error) throw error; return cls }
export async function getLessons(classId:string) { const {data,error}=await supabase.from('lessons').select('*').eq('class_id',classId).order('created_at',{ascending:false}); if(error) throw error; return data||[] }
export async function createLesson(classId:string,title:string,description:string,published=true) { const id=await userId(); const {data,error}=await supabase.from('lessons').insert({class_id:classId,teacher_id:id,title,description,published}).select().single(); if(error) throw error; return data }
export async function getAssignments(classId:string) { const {data,error}=await supabase.from('assignments').select('*').eq('class_id',classId).order('due_at',{ascending:true}); if(error) throw error; return data||[] }
export async function getMySubmission(assignmentId:string) { const id=await userId(); const {data,error}=await supabase.from('assignment_submissions').select('*').eq('assignment_id',assignmentId).eq('student_id',id).order('submitted_at',{ascending:false}).limit(1).maybeSingle(); if(error) throw error; return data }
export async function getSubmissions(assignmentId:string) { const {data,error}=await supabase.from('assignment_submissions').select('*, profiles:student_id(full_name)').eq('assignment_id',assignmentId).order('submitted_at',{ascending:false}); if(error) throw error; return data||[] }
export async function createAssignment(classId:string,title:string,description:string,dueAt:string,maxPoints=100) { const id=await userId(); const {data,error}=await supabase.from('assignments').insert({class_id:classId,teacher_id:id,title,description,due_at:dueAt||null,status:'published',max_points:maxPoints}).select().single(); if(error) throw error; return data }
export async function submitAssignment(assignmentId:string,content:string) { const id=await userId(); const {data,error}=await supabase.from('assignment_submissions').insert({assignment_id:assignmentId,student_id:id,content,submitted_at:new Date().toISOString(),status:'submitted'}).select().single(); if(error) throw error; return data }
export async function gradeSubmission(submissionId:string,score:number,feedback:string) { const id=await userId(); const {data,error}=await supabase.from('assignment_submissions').update({score,feedback,status:'graded',graded_by:id,graded_at:new Date().toISOString()}).eq('id',submissionId).select().single(); if(error) throw error; return data }

export async function getQuizzes(classId:string) { const {data,error}=await supabase.from('quizzes').select('*, quiz_questions(*, quiz_options(id,option_text,position))').eq('class_id',classId).order('created_at',{ascending:false}); if(error) throw error; return data||[] }
export async function createQuiz(classId:string,title:string,description:string) { const id=await userId(); const {data,error}=await supabase.from('quizzes').insert({class_id:classId,teacher_id:id,title,description,published:true}).select().single(); if(error) throw error; return data }
export async function addQuizQuestion(quizId:string,questionText:string,options:string[],correctIndex:number,points=1) { const {data:q,error}=await supabase.from('quiz_questions').insert({quiz_id:quizId,question_text:questionText,question_type:'multiple_choice',points,position:0}).select().single(); if(error) throw error; const rows=options.map((option_text,i)=>({question_id:q.id,option_text,is_correct:i===correctIndex,position:i})); const {error:oe}=await supabase.from('quiz_options').insert(rows); if(oe) throw oe; return q }
export async function submitQuizAttempt(quizId:string,answers:{question_id:string;selected_option_id?:string;answer_text?:string}[]) { const {data,error}=await supabase.rpc('submit_quiz_attempt',{p_quiz_id:quizId,p_answers:answers}); if(error) throw error; return data }

export async function getAttendance(classId:string) { const {data,error}=await supabase.from('attendance').select('*, profiles:student_id(full_name)').eq('class_id',classId).order('attendance_date',{ascending:false}); if(error) throw error; return data||[] }
export async function recordAttendance(classId:string,studentId:string,status:'present'|'absent'|'late'|'excused',note='') { const id=await userId(); const {data,error}=await supabase.from('attendance').upsert({class_id:classId,student_id:studentId,attendance_date:new Date().toISOString().slice(0,10),status,note,recorded_by:id},{onConflict:'class_id,student_id,attendance_date'}).select().single(); if(error) throw error; return data }
export async function getGrades(classId:string) { const {data,error}=await supabase.from('grades').select('*, profiles:student_id(full_name)').eq('class_id',classId).order('graded_at',{ascending:false}); if(error) throw error; return data||[] }
export async function addGrade(classId:string,studentId:string,title:string,score:number,maxScore:number,feedback='') { const id=await userId(); const {data,error}=await supabase.from('grades').insert({class_id:classId,student_id:studentId,title,score,max_score:maxScore,feedback,assessment_type:'manual',graded_by:id}).select().single(); if(error) throw error; return data }
export async function getAnnouncements(classId:string) { const {data,error}=await supabase.from('announcements').select('*').eq('class_id',classId).order('created_at',{ascending:false}); if(error) throw error; return data||[] }
export async function createAnnouncement(classId:string,title:string,content:string) { const id=await userId(); const {data,error}=await supabase.from('announcements').insert({class_id:classId,author_id:id,title,content,published:true}).select().single(); if(error) throw error; return data }
export async function getNotifications() { const id=await userId(); const {data,error}=await supabase.from('notifications').select('*').eq('user_id',id).order('created_at',{ascending:false}).limit(30); if(error) throw error; return data||[] }
export async function markNotificationRead(notificationId:string) { const id=await userId(); const {error}=await supabase.from('notifications').update({read_at:new Date().toISOString()}).eq('id',notificationId).eq('user_id',id); if(error) throw error }
